scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: application
    scrape_interval: 5s
    metrics_path: /api/metrics
    static_configs:
      - targets: ['server:5001']